### ISSUE TITLE
Rückmeldung zur Definition der Views

### ISSUE THREAD

**Issue by schmandr** [sogis/searchservice#1]
### Mit Null-Werten rechnen

https://github.com/sogis/searchservice/blob/512975587824155c0f5cd739bf06bbf76d9fb22b/sourcedb/ddl_script/testing_views.sql#L7

Das Attribut `objectval` kann im konkreten Fall auch Null sein, da keine Constraint auf dem Attribut ist. Mit dem Concatenation Operator wäre in diesem Fall der gesamte _displaytext_ Null. Abhilfe könnte hier die Funktion `concat(string, string, ...)` schaffen, die Null-Werte allerdings einfacht ignoriert. (Sie akzeptiert auch Zahlenwerte.) Doku siehe https://www.postgresql.org/docs/11/functions-string.html.
Und dann köntest du gerade die Funktion `concat_ws(separator, string, string, ...)` nehmen mit einem Leerschlag als Separator. Dies macht die "Konstruktion" der Strings etwas weniger Fehleranfällig bezüglich den Leerschlägen, und die  Skripte übersichtlicher.
Gilt für alle Zeilen mit dem Concatenation Operator.

### Array einfacher erzeugen

https://github.com/sogis/searchservice/blob/512975587824155c0f5cd739bf06bbf76d9fb22b/sourcedb/ddl_script/testing_views.sql#L15

Dies ginge wohl auch etwas eifacher mit
`(array_to_json(ARRAY[subclass::text, id_in_class::text]))::text AS id`
statt
`(array_to_json(array_append(ARRAY[subclass::text], id_in_class::text)))::text AS id`.
Doku: https://www.postgresql.org/docs/11/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS
Gilt auch für Zeile 20 und für die anderen Views.

### Datenquelle, und Name der View

https://github.com/sogis/searchservice/blob/512975587824155c0f5cd739bf06bbf76d9fb22b/sourcedb/ddl_script/testing_views.sql#L33

Weshalb nimmst du nicht `agi_hoheitsgrenzen_pub.hoheitsgrenzen_bezirksgrenze`? Dann wäre der Name der View auch nicht so kompliziert. Falls es einen bestimmten Grund dafür gibt, dann wäre noch eine Überlegung wert, ob die View z.B. auch _agi_hoheitsgrenzen_pub.hoheitsgrenzen_bezirke_solr_v_ heissen könnte, weil einfacher.

### Vorschlag Suchbegriffe

https://github.com/sogis/searchservice/blob/512975587824155c0f5cd739bf06bbf76d9fb22b/sourcedb/ddl_script/testing_views.sql#L94

Das sind so die Suchstichwörter dafür? Hier sucht man evtl. auch nach "Liegenschaft".

**Comment by bjsvwcur** [comment]
Bei der Funktion concat_ws(separator, string, string, ...) wird
aus
"concat_ws('Fundstellen-Nr.: ',fundstellennummer,' (Punktfundstelle ungeschützt)') AS displaytext,"
wird
displaytext = "115/301Fundstellen-Nr.:  (Flächenfundstelle geschützt)"

Ich wende die Funktion _concat_ an.

**Comment by schmandr** [comment]
Die Funktion concat_ws funktioniert so, dass der erste Parameter der Separator ist, und alle folgenden Parameter die Strings, die zusammengehängt werden sollen. Dein Beispiel müsste also so lauten:

`concat_ws(' ', 'Fundstellen-Nr.:', fundstellennummer, '(Punktfundstelle ungeschützt)')`
